### ISSUE TITLE
Project gives Compiler error when run on Android studio 3.1.4

### ISSUE THREAD

**Issue by ParikshitTiwari** [LLhon/Android-Video-Editor#1]
error: package com.coremedia.iso.boxes does not exist	
error: package com.googlecode.mp4parser.authoring does not exist	
error: package com.googlecode.mp4parser.authoring.container.mp4 does not exist	
error: package com.googlecode.mp4parser.authoring.tracks does not exist	
error: package com.googlecode.mp4parser.authoring.tracks does not exist	

how to fix this.

**Comment by LLhon** [comment]
> error: package com.coremedia.iso.boxes does not exist
> error: package com.googlecode.mp4parser.authoring does not exist
> error: package com.googlecode.mp4parser.authoring.container.mp4 does not exist
> error: package com.googlecode.mp4parser.authoring.tracks does not exist
> error: package com.googlecode.mp4parser.authoring.tracks does not exist
> 
> how to fix this.

My operating environment is 3.1.4，Try adding this compile 'com.googlecode.mp4parser:isoparser:1.1.21'

**Comment by HiJohn** [comment]
同样的问题

加了implementation 'com.googlecode.mp4parser:isoparser:1.1.21'
之后编译报错：
More than one file was found with OS independent path 'builddef.lst'

**Comment by LLhon** [comment]
> 同样的问题
> 
> 加了implementation 'com.googlecode.mp4parser:isoparser:1.1.21'
> 之后编译报错：
> More than one file was found with OS independent path 'builddef.lst'

libs里面是有一个isoparser-1.0.6.jar包，应该是加重复了

**Comment by HiJohn** [comment]
> > 同样的问题
> > 加了implementation 'com.googlecode.mp4parser:isoparser:1.1.21'
> > 之后编译报错：
> > More than one file was found with OS independent path 'builddef.lst'
> 
> libs里面是有一个isoparser-1.0.6.jar包，应该是加重复了

嗯删除就好了
